import sqlite3
import yfinance as yf

recomeçar = True ######################################################################################################################################################################################################################
while recomeçar:                                                                                                                                                                                                                      #
                                                                                                                                                                                                                                      #
   todosSimbolos = ['BIDI4.SA', 'PINE4.SA', 'AZEV4.SA'] #### Lista de simobolos que sera atualizado e os que nunca foi inserido no meu BD                                                                                             #
                                                                                                                                                                                                                                      #
   con = sqlite3.connect('banco-de-dados.db')############### Conecta no BD responsavel por guardar preço de data(id),                                                                                                                 #
   cursor = con.cursor()                                   # abertura, minima, maxima, fechamento e volume                                                                                                                            #
                                                                                                                                                                                                                                      #
   cursor.execute("SELECT name FROM sqlite_master WHERE type='table';") #################################                                                                                                                             #
   rows = cursor.fetchall()                                                                             #                                                                                                                             #
   selectSymbols = []                                                                                   ##### Começamos selecionando todos que já existe                                                                              #
   for i in rows:                                                                                       #  no nosso BD, mas falta ser atualizado, depois                                                                              #
       listNumbers = list(i)                                                                            #  de selecionado colocamos em uma lista                                                                                      #
       selectSymbols.append(listNumbers) ################################################################                                                                                                                             #
                                                                                                                                                                                                                                      #
   ativosExistenteNoBD = [] #############################################################################                                                                                                                             #
   for elemento in selectSymbols:                                                                       #                                                                                                                             #
       if isinstance(elemento, list):                   #   Aqui convertemos "ativosExistenteNoBD"      #                                                                                                                             #
           for subelemento in elemento:                 #   que existe no BD que esta no formato        #                                                                                                                             #
               ativosExistenteNoBD.append(subelemento) ##   de tupla em lista                           #                                                                                                                             #
       else:                                            #                                               #### Criamos duas listas de simbolos, as que já existem no BD                                                                 #
           ativosExistenteNoBD.append(elemento)         #                                               #  e as que vai ser inserida pela primeira vez                                                                                #
                                                                                                        #                                                                                                                             #
   ativosNaoExistenteNoBD = []                          #   Nesse pedaço de codigo comparamos a         #                                                                                                                             #
   for i in todosSimbolos:                              #   'ativosExistenteNoBD' e  'todosSimbolos',   #                                                                                                                             #
       existe = i in ativosExistenteNoBD  ###############   o resultado é 'ativosNaoExistenteNoBD'      #                                                                                                                             #
       if existe == False:                              #   nosso banco de dados                        #                                                                                                                             #
           ativosNaoExistenteNoBD.append(i)             #                                               #                                                                                                                             #
   print(ativosExistenteNoBD)                                                                           #                                                                                                                             #
   print(ativosNaoExistenteNoBD) ########################################################################                                                                                                                             #
                                                                                                                                                                                                                                      #
                                                                                                                                                                                                                                      #
   contandoAtivosNaoExistenteNoBD = len(ativosNaoExistenteNoBD) #########################################                                                                                                                             #
   periodoMax = []                                                                                      #### Contamos o numero de elementos que existir na lista 'ativosNaoExistenteNoBD'.                                            #
   for item in range(contandoAtivosNaoExistenteNoBD):###  Esse laço conta e 'ativosNaoExistenteNoBD'    # e criamos uma outra lista que vai se chamar 'periodoMax'. Essa nova lista vai ter o mesmo                                   #
       maximo = 'max'                                  #  e imprime 'max' o numero de vez necessario    # tamanhos que  'ativosNaoExistenteNoBD' e vai quardar o tamanho do arquivo que vamos baixair                                 #
       periodoMax.append(maximo)                                                                        # do yahoo finance. Quando ser 'ativosNaoExistenteNoBD', o tamanho vai ser sempre  'max' que significa maximo                 #
   print(periodoMax) ################################################################################                                                                                                                             #
                                                                                                                                                                                                                                      #
   #######################################################################################################                                                                                                                             #
   #                                                                                                     #                                                                                                                             #
   getQtsDiasTemNaSemanaConcatenado = []###  Essa lista vai guardar o resultado do If abaixo             #                                                                                                                             #
   ativosVaoSerAtualizado = []            #  Essa lista vai guardar o resultado do If abaixo             #                                                                                                                             #
                                                                                                         ##### Se existir um ativo cadastrado no nosso BD                                                                              #
   contarAtivosExistenteNoBD = len(ativosExistenteNoBD)#### Essa condicional é pouco importante, ela faz #    verificamos se ele estar desatualizado.                                                                                  #
   if contarAtivosExistenteNoBD >= 1:                     # mais sentido quando nenhum ativo foi cadas-  #    O codigo abaixo é necessario para ver quantos dias                                                                       #
                                                          # no BD                                        #    ele esta desatualizado, assim conseguimos chegar no numero                                                               #
                                                                                                         #    certo de informações que deve ser baixada do nosso provedor, q                                                           #
                                                                                                         #    no caso é o Yahoo Finance.                                                                                               #
       getDiaAtual = []                                                                                  #                                                                                                                             #
       from datetime import date #######                                                                 #                                                                                                                             #
       diaAtual = date.today()        ## Selecionamos o dia atual                                        #
       diaAtualString = str(diaAtual) # vamos usar mais tarde                                            #                                                                                                                             #
       getDiaAtual.append(diaAtualString)                                                                #                                                                                                                             #
       print(diaAtualString)###########                                                                  #                                                                                                                             #
                                                                                                         #                                                                                                                             #
       getTodosUltSalvo = []###########################################                                  #                                                                                                                             #
       for get, nome in zip(ativosExistenteNoBD, ativosExistenteNoBD):####Na ordem, coletamos do nosso   #                                                                                                                             #
           cursor.execute('SELECT MAX(Id) FROM "' + str(nome) + '"')  #   bd, o Id q é a Data da ultima  #                                                                                                                             #
           rows = cursor.fetchone()                                   #   vez que foi atualizado  e      #                                                                                                                             #
           ultSalvo = []                                              #   colocamos em uma lista         #                                                                                                                             #
           for elemento in rows:                                      #                                  #                                                                                                                             #
               if isinstance(elemento, list):                         ####Os dados coletados em formato  #                                                                                                                             #
                       ultSalvo.append(subelemento)                   #   em formato de lista            #                                                                                                                             #
               else:                                                  #                                  #                                                                                                                             #
                   ultSalvo.append(elemento)                          ####Formatamos os elementos da     #                                                                                                                             #
           ultimoSalvo = str(ultSalvo).strip('[]')                    #   lista e deixamos ele no formato#                                                                                                                             #
           ultimaSalvo = ultimoSalvo.replace("'", '')                 #   certo pra interagir na proxima #                                                                                                                             #
           getTodosUltSalvo.append(ultimaSalvo)                       #   função                         #                                                                                                                             #
       print(getTodosUltSalvo)   ######################################                                  #                                                                                                                             #
                                                                                                         #                                                                                                                             #
       from datetime import datetime  #################################                                  #                                                                                                                             #
       getTodosQntDias = []                                           ## Transformamos 'getTodosUltSalvo'#                                                                                                                             #
       getDayUltimoSalvo = []                                         # que é uma lista de string em uma #                                                                                                                             #
       for c in getTodosUltSalvo:                                     # lista de datetime                #                                                                                                                             #
           dayUltimoSalvo = datetime.strptime(c, '%Y-%m-%d')          #                                  #                                                                                                                             #
                                                                      #                                  #                                                                                                                             #
           dayAtual = datetime.strptime(diaAtualString, '%Y-%m-%d')   #### Agora fazemos uma subtração,  #                                                                                                                             #

           quantidade_dias = abs((dayUltimoSalvo - dayAtual).days)    #'diaAtualString' - 'dayUltimoSalvo'#                                                                                                                             #
           getTodosQntDias.append(quantidade_dias)                    # o resultado dessa subtração é o  #                                                                                                                             #
           getDayUltimoSalvo.append(dayUltimoSalvo)                   # numero de dias que o bd esta     #                                                                                                                             #
       print(getTodosQntDias)                                         # desatualizado q no caso é        #                                                                                                                             #
       print(getDayUltimoSalvo)                                       # representado por getTodosQntDias.#                                                                                                                             #
                                                                      # Porem precisamos retirar os dias #                                                                                                                             #
                                                                  # que a bolsa  esteve fechada, no  #                                                                                                                             #
                                                                      # caso feriados e final de semana  #                                                                                                                             #
   ####################################################################                                  #                                                                                                                             #
                                                                                                         #                                                                                                                             #
       #  Começaos tirar os dias indesejados                                                             #                                                                                                                             #
                                                                                                         #                                                                                                                             #
       import datetime  ##################################################                               #                                                                                                                             #
       getDataList = []                                                  ### Entao aqui criamos uma      #                                                                                                                             #
       for d, t in zip(getDayUltimoSalvo, getTodosQntDias):              # lista de datas que parte de   #                                                                                                                             #
           dataList = [d + datetime.timedelta(days=x) for x in range(t)] # 'getDayUltimoSalvo' e vai ate #                                                                                                                             #
           getDataList.append(dataList)                                  # a data de hoje                #                                                                                                                             #
       print(getDataList)                                                #                               #                                                                                                                             #
                                                                         #                               #                                                                                                                             #
       convertListaDiasString = []                                       #### O 'getDataList' esta no    #                                                                                                                             #
       for d in getDataList:                                             # formato datetime, convertemos #                                                                                                                             #
           convertListaDias = []                                         # ele em string                 #                                                                                                                             #
           for i in d:                                                   #                               #                                                                                                                             #
               dateStr = str(i)                                          #                               #                                                                                                                             #
               limpDate = dateStr[0:10]                                  #                               #                                                                                                                             #
               convertListaDias.append(limpDate)                         #                               #                                                                                                                             #
           convertListaDiasString.append(convertListaDias) ###############                               #                                                                                                                             #
       print(convertListaDiasString)                                                                     #                                                                                                                             #
                                                                                                         #                                                                                                                             #
       getTirarUltimoSave = []                                                                           #                                                                                                                             #
       for l, u in zip(convertListaDiasString, getTodosUltSalvo):### Tiramos o ultimo dia que foi        #                                                                                                                             #
                                                                  # atualizado                           #                                                                                                                             #
           tiraUltimoSalvo = []                                   #                                      #                                                                                                                             #
           for c in l:                                            #                                      #                                                                                                                             #
               existe = c in u                                    #                                      #                                                                                                                             #
               if existe == False:                                #                                      #                                                                                                                             #
                   tiraUltimoSalvo.append(c)                      #                                      #                                                                                                                             #
           getTirarUltimoSave.append(tiraUltimoSalvo) #############                                      #                                                                                                                             #
       print(getTirarUltimoSave)                                                                         #                                                                                                                             #
                                                                                                         #                                                                                                                             #
       feriados = ['2020-02-24', '2020-02-25', '2020-04-10', '2020-04-21', '2020-05-01',### Retiramos    #                                                                                                                             #
                   '2020-06-11', '2020-09-07', '2020-10-12', '2020-11-02', '2020-12-24', # os feriados   #                                                                                                                             #
                   '2020-12-25', '2020-12-31', '2020-07-09', '2020-11-20']               #               #                                                                                                                             #
       getTiraFeriadosDaListaDeDias = []                                                 #               #                                                                                                                             #
       for g in getTirarUltimoSave:                                                      #               #                                                                                                                             #
           tiraFeriadosDaListaDeDias = []                                                #               #                                                                                                                             #
           for c in g:                                                                   #               #                                                                                                                             #
               existe = c in feriados                                                    #               #                                                                                                                             #
               if existe == False:                                                       #               #                                                                                                                             #
                   tiraFeriadosDaListaDeDias.append(c)                                   #               #                                                                                                                             #
           getTiraFeriadosDaListaDeDias.append(tiraFeriadosDaListaDeDias) ################               #                                                                                                                             #
       print('TIRA FERIADOS' + str(getTiraFeriadosDaListaDeDias))                                        #                                                                                                                             #
                                                                                                         #                                                                                                                             #
       from datetime import datetime    ################################ Retirando finais de semana      #                                                                                                                             #
       dias = ['Segunda-feira', 'Terça-feira', 'Quarta-feira',      #  ou seja 'Sábado' e'Domingo'       #                                                                                                                             #
               'Quinta-Feira', 'Sexta-feira', 'Sábado', 'Domingo']  #                                    #                                                                                                                             #
       getDiasDaSemana = []                                         #                                    #                                                                                                                             #
       for g in getTiraFeriadosDaListaDeDias:                       #                                    #                                                                                                                             #
           diasDaSemana = []                                        #                                    #                                                                                                                             #
           for c in g:                                              #### Aqui trasformamos a lista de    #                                                                                                                             #
               datetime_object = datetime.strptime(c, "%Y-%m-%d")   #   datas em dias da semana          #                                                                                                                             #
               indice_da_semana = datetime_object.weekday()         #                                    #                                                                                                                             #
               dia_da_semana = dias[indice_da_semana]               #                                    #                                                                                                                             #
               diasDaSemana.append(dia_da_semana)                   #                                    #                                                                                                                             #
           getDiasDaSemana.append(diasDaSemana)                     ####                                 #                                                                                                                             #
       print(getDiasDaSemana)                                           #                                #                                                                                                                             #
       finaisDeSemana = ['Sábado', 'Domingo']                            #                               #                                                                                                                             #
       getLimpoDeFinaisDeSemanaDaLista = []                               #                              #                                                                                                                             #
       for g in getDiasDaSemana:                                           #                             #                                                                                                                             #
           tiraFinaisDeSemanaDaListaDeDias = []                             #                            #                                                                                                                             #
           for c in g:                                                       #                           #                                                                                                                             #
               existe = c in finaisDeSemana                                   #                          #                                                                                                                             #
               if existe == False:                                             #                         #                                                                                                                             #
                   tiraFinaisDeSemanaDaListaDeDias.append(c)                    ###                      #                                                                                                                             #
           getLimpoDeFinaisDeSemanaDaLista.append(tiraFinaisDeSemanaDaListaDeDias)#                      #                                                                                                                             #
       print('TIRA FINAIS DE SEMANA' + str(getLimpoDeFinaisDeSemanaDaLista))                             #                                                                                                                             #
                                                                                                         #                                                                                                                             #
       for c, ativos in zip(getLimpoDeFinaisDeSemanaDaLista, ativosExistenteNoBD):#### Resultado Final   #                                                                                                                             #
           if c != []:                                                              # de quantos dias    #                                                                                                                             #
               contarQtsDiasTemNaSemana = len(c)                                    # vão ser atualizado #                                                                                                                             #
               contarQtsDiasTemNaSemanaString = str(contarQtsDiasTemNaSemana)       # e quais ativos que #                                                                                                                             #
               concatenarQtsDiasTemNaSemana = contarQtsDiasTemNaSemanaString + 'd'  # estao no nosso BD  #                                                                                                                             #
               getQtsDiasTemNaSemanaConcatenado.append(concatenarQtsDiasTemNaSemana)# vai ser atualizado #                                                                                                                             #
               ativosVaoSerAtualizado.append(ativos)                                                     #                                                                                                                             #
               print(getQtsDiasTemNaSemanaConcatenado)####################################################                                                                                                                            #
                                                                                                                                                                                                                                      #
                                                                                                                                                                                                                                      #
                                                                                                                                                                                                                                      #
   somaPeriodos = periodoMax + getQtsDiasTemNaSemanaConcatenado #########################################                                 1 lista guarda o periodo que vai ser requisitado no nosso proveddor                         #
   somaAtivos = ativosNaoExistenteNoBD + ativosVaoSerAtualizado                                         ### Ent aqui criamos duas listas:  2 lista leva o nome todos os ativos, os que já estao no BD                                 #
   contarSomaPeriodos = len(somaPeriodos) ###############################################################                                    e os que vai ser inserido pela primeira vez                                              #
                                                                                                                                                                                                                                      #
                                                                                                                                                                                                                                      #
                                                                                                                                                                                                                                      #
                            ############################################################################                                                                                                                      #########
   if contarSomaPeriodos >= 1:                                                                         #### Com as duas listas ja formadas iniciamos                                                                          #
        getInformaçõesDoPreço = []##                                                                   # o download das informações que estao no site                                                                         #
        getId = []                 #                                                                   # Yahoo Finance                                                                                                        #
        getNomeDoAtivo = []        ### Onde os resultados vao ser guardados                            #                                                                                                                      #
        getTamanhoDaLista = []######                                                                   #                                                                                                                      #
        restart = True                                                                                 #                                                                                                                      #
        while restart:                                                                                 #                                                                                                                      #
            for simbolos, periodos in zip(somaAtivos, somaPeriodos ):### Testamos a conexão, se estiver#                                                                                                                      #
                import urllib                                        # conectado ele executa o         #                                                                                                                      #
                def connected(host='http://google.com'):             # download, se a internet cair    #                                                                                                                      #
                    try:                                             # ele zera tudo que já baixou e   #                                                                                                                      #
                        urllib.request.urlopen(host)                 # começa baixar tudo do zero      #                                                                                                                      #
                        return True                                  #                                 #                                                                                                                      #
                    except:                                          #                                 #                                                                                                                      #
                        return False                                 #                                 #                                                                                                                      #
                c = connected() ######################################                                 #                                                                                                                      #
                if c == True:                                                                          #                                                                                                                      #
                    data = yf.download(simbolos, period=periodos)################ Aqui executamos a    #                                                                                                                      #
                    price = data[['Open', 'High', 'Low', 'Close', 'Volume']] # requisição no site do   #                                                                                                                      #
                    result = price.values.tolist()                           # Yahoo Finance           #                                                                                                                      #
                    id = price.index.tolist()                                #                         #                                                                                                                      #
                    getInformaçõesDoPreço.append(result)                     #                         #                                                                                                                      #
                    getNomeDoAtivo.append(simbolos)                          #                         #                                                                                                                      #
                    getId.append(id)                                         #                         #                                                                                                                      #
                    contar = len(id)                                         #                         #                                                                                                                      #
                    getTamanhoDaLista.append(contar)##########################                         #                                                                                                                      #
                else:                                                                                  #                                                                                                                      #
                    print('sem internet')                                                              #                                                                                                                      #
                    break                       ############### Aqui ele verifica se ja foi feito      #                                                                                                                      #
            contarTodosSimbolos = len(somaAtivos)          # todo download, se sim ele sai do while    #                                                                                                                      #
            contarGetNomeDoAtivo = len(getNomeDoAtivo)     # com todas as informações necessarias para #                                                                                                                      #
            if contarTodosSimbolos == contarGetNomeDoAtivo:# o nosso BD ficar atualizado               #                                                                                                                      #
                break                                                                                  #                                                                                                                      #
                ########################################################################################                                                                                                                      #
                                                                                                                                                                                                                              #
        eleminandoDadosFalso = [] ######################################################################### Agora limpamos os dados e o salvamos                                                                              #
        getVezesDeCadaAtivo = []                                                                       #                                                                                                                      #
        for res, id, c in zip(getInformaçõesDoPreço,getId, getNomeDoAtivo ):### Limpampos os dados     #                                                                                                                      #
            for r, i in zip(res, id):                                       #                          #                                                                                                                      #
                dateStr = str(i)                                            #                          #                                                                                                                      #
                idLimp = dateStr[0:10]                                      #                          #                                                                                                                      #
                r.insert(0, idLimp)
                print(r);
                print(idLimp);
                resultado = 0.0 in r or dateStr in idLimp            #                          #                                                                                                                      #
                if resultado == False:                                      #                          #                                                                                                                      #
                    eleminandoDadosFalso.append(r)                          #                          #                                                                                                                      #
                    getVezesDeCadaAtivo.append(c)############################                          #                                                                                                                      #
                                                                                                       #                                                                                                                      #
        for dados, nome in zip(eleminandoDadosFalso, getVezesDeCadaAtivo):##### E salvamos             #                                                                                                                      #
            cursor.execute("create table if not exists'" + str(nome) +      #                          #                                                                                                                      #
                           "' (Id, Open, High, Low, Close, Volume)")        #                          #                                                                                                                      #
            cursor.execute("INSERT INTO'" + str(nome) +                     #                          #                                                                                                                      #
                           "'(Id, Open, High, Low, Close, Volume) "         #                          #                                                                                                                      #
                           "VALUES(?,?,?,?,?,?)",(dados))                   #                          #                                                                                                                      #
            con.commit()  ###################################################                          #                                                                                                                      #
                                                                                                       #                                                                                                                      #
                  ######### Se precisar esperar os dados do Yahoo Finance atualizar                    #                                                                                                                      #
        import time    #     rodamos o script mais uma vez, mas antes esperamos mais 15 minutos        #                                                                                                                      #
        time.sleep(900)#     pra rodar mais uma vez                                                    #                                                                                                                      #
                  ######                                                                               #                                                                                                                      #
                                                                                                       #                                                                                                                      #
        ################################################################################################                                                                                                                      #
   else:                                                                                                                                                                                                                      #
       print('Banco de Dados Atualizado')######################################################################################################################################################################################
       break

